name: Annotate Comments
description: Create GitHub Workflow annotations from comments in code.

inputs:
  pattern:
    description: Override default regex pattern passed to grep.
    required: false

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: annotate.sh
      shell: bash
      env:
        PATTERN: ${{ inputs.pattern }}
