name: Annotate Comments
description: Create GitHub Actions annotations from comments in code.
author: Joonas Häkkinen

inputs:
  pattern:
    description: Override default regex pattern passed to grep.
    required: false
  include:
    description: Include only files matching given glob pattern. By default, all files are included.
    required: false
  working-dir:
    description: Directory to run action in. Note that setting this also affects the scope of include param.
    required: false
    default: .

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: annotate.sh
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      env:
        PATTERN: ${{ inputs.pattern }}
        INCLUDE: ${{ inputs.include }}

branding:
  icon: message-square
  color: gray-dark
