name: Annotate Comments
description: Create GitHub Workflow annotations from comments in code.

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: annotate.sh
      shell: bash
